### ISSUE TITLE
Post conversion, the download feature saves the final file with a *.txt extension.

### ISSUE THREAD

**Issue by hargovindsingh** [Hartley-Madison-215062417/Hashir-Jamil-EECS-2311-Group11#14]
**Reported by:**
Hargovind Singh
 
**Date reported:**
March 24th, 2021
 
**Program (or component) name:**
After the download/conversion is completed
 
**Configuration(s):**
Operating System: Windows 10 Pro 64
Manufacturer and Model: HP Notebook
Processor: Intel® Core™ i5-10210U
Memory: 8 GB (RAM)
JAVA version: Java-SE 15
Screen size: 15 inch
Application Version: Downloaded from Github master March 24th. Commit key: feb0ce0
 
**Reproducibility:**
Yes
 
**Severity:**
Medium
 
**Problem Summary:**
Post conversion, the download feature saves the file with a *.txt extension.
**Problem description**
Post conversion, when I click download and put the name of the file and click save, the file gets saved in the wrong format (*.txt).
 
**Expected Behaviour:**
The extension should be .musicxml
 
**Steps to Reproduce:**
Import the master branch in Eclipse from git import
Right-click on the project -> Gradle -> Refresh Gradle
Click on Run
In the pop-up screen, click on Start.
Click on "Choose a tablature file" -> Upload file
Click on "Download" -> Select Location -> Set extension to .musicxml -> Click "Save"
Find the dile on the system, you will see that the file has a *.txt extension.
 
**New or old bug:**
New

**Comment by gilmore35** [comment]
Thank you for your bug report. The output file can now be downloaded with a .musicxml extension.
