### ISSUE TITLE
Downloaded file in a text file instead of .musicxml

### ISSUE THREAD

**Issue by zhouziqi13** [Hartley-Madison-215062417/Hashir-Jamil-EECS-2311-Group11#4]
## Bug Report Title:
Downloaded file in a text file instead of .musicxml

### Reported by:  
Ziqi Zhou
### Date reported:
March 23rd, 2021
### Program (or component) name: 
Download process after the conversion is complete
### Configuration(s):
***Operating System***: MacOS Big Sur 

***Manufacturer and Model***: MacBook Air (M1, 2020)

***Processor:*** Apple M1

***Memory***: 8 GB (RAM)  

***Graphics Card:*** Apple M1 GPU 8 GB

***JAVA version***: Java-SE 15

***Application Version***: Downloaded from Github master March 23rd. Commit key: https://github.com/Hartley-Madison-215062417/Hashir-Jamil-EECS-2311-Group11/commit/45152c12188941611a7778e124912d83136b06b8

### Report type:  
Coding Error
### Reproducibility:  
Yes  
### Severity:  
Medium
### Problem Summary:  
After the conversion is complete, the download button will automatically save the converted content as a .txt file.
### Problem description:  
When the conversion is complete, the download button opens up a file saving screen with default file format ".txt". Even if the user attempt to change the file format, the saved file will have a file format of .musicxml.txt.

### Expected Behaviour:
The saved file needs to be .musicxml file.

### Steps to Reproduce: 
Import the master branch in Eclipse from git import 

Right-click on the project -> Gradle -> Refresh Gradle

Click on Run

In the pop-up screen, click on Start.

Click on "Choose a tablature file" -> Upload a text file containing a tablature 

Click on "Download" -> Select a desired location -> Changed the file extension to .musicxml -> Click "Save"

Go to the location where the file is saved, notice the file has the extension of .musicxml.txt
### New or old bug:
New  

### Screenshot
<img width="139" alt="Screen Shot 2021-03-24 at 11 45 02 AM" src="https://user-images.githubusercontent.com/46424591/112339859-6c9acf00-8c96-11eb-9cd3-089411439723.png">

**Comment by gilmore35** [comment]
Thank you for the bug report. Our app now lets users download .musicxml files.
